### ISSUE TITLE
missing font name parameter in example "3.7.2. Rendering Text"

### ISSUE THREAD

**Issue by roipeker** [Starling-Manual/Starling-Manual-EN#2]
In "3.7.2. Rendering Text", [msdf-bmfont-xml
](http://manual.starling-framework.org/en/#_msdf_bmfont_xml) the example,
`TextField.registerCompositor(font);` is missing the font name parameter, according to Starling's v2.3 master API.

**Comment by PrimaryFeather** [comment]
Thanks a lot for the heads-up! Fixed with 10ca48960fdd.
